version: '3'

services:
  mongo:
    image: mongo:4.0.17-xenial
    container_name: ca-mongo
    logging:
      driver: none
    volumes:
      - ./db:/data/db
  idxMongo:
    image: mongo:4.0.17-xenial
    container_name: ca-idx
    logging:
      driver: none
    links:
      - mongo
    volumes:
      - ./config:/config
    command:
      - /config/run_idx.sh
    depends_on:
      - mongo
    tty: true
    stdin_open: true
  back:
    build:
      context: "../Caracal"
      args:
        viewer: "develop"
    depends_on:
      - "mongo"
    ports:
      - "4010:4010"
    container_name: ca-back
    volumes:
      - ./config/login.html:/root/src/static/login.html
      - ./jwt_keys/:/root/src/keys/
      - ../caMicroscope:/root/src/camicroscope
    environment:
      JWK_URL: "https://www.googleapis.com/oauth2/v3/certs"
      IIP_PATH: "http://ca-iip/fcgi-bin/iipsrv.fcgi"
      MONGO_URI: "mongodb://ca-mongo"
      DISABLE_SEC: "true"
      ALLOW_PUBLIC: "true"
  iip:
    image: camicroscope/iipimage:latest
    container_name: ca-iip
    restart: unless-stopped
    volumes:
      - ./images/:/images/
  loader:
    build: "https://github.com/camicroscope/SlideLoader.git#develop"
    container_name: ca-load
    volumes:
      - ./images/:/images/
