version: '3'

services:
  mongo:
    image: mongo:4.0-xenial
    container_name: ca-mongo
    restart: unless-stopped
    volumes:
      - ./db:/data/db
  idxMongo:
    image: mongo:4.0-xenial
    container_name: ca-idx
    links:
      - mongo
    volumes:
      - ./config:/config
    command:
      - /config/run_idx.sh
    depends_on:
      - mongo
  back:
    image: camicroscope/caracal:latest
    depends_on:
      - "mongo"
    ports:
      - "4010:4010"
    environment:
      JWK_URL: "https://www.googleapis.com/oauth2/v3/certs"
      IIP_PATH: "http://ca-iip:8080/fcgi-bin/iipsrv.fcgi"
      MONGO_URI: "mongodb://ca-mongo"
    container_name: ca-back
    volumes:
      - ./config/login.html:/src/static/login.html
      - ./jwt_keys/:/src/keys/
      - ./config/routes.json:/src/routes.json
      - ./config/contentSecurityPolicy.json:/src/contentSecurityPolicy.json
  iip:
    image: camicroscope/iipimage:latest
    container_name: ca-iip
    restart: unless-stopped
    volumes:
      - ./images/:/images/
  loader:
    image: camicroscope/slideloader:latest
    container_name: ca-load
    restart: unless-stopped
    volumes:
      - ./images/:/images/
